### ISSUE TITLE
Interesting project

### ISSUE THREAD

**Issue by freaad** [anish9/Fashion-AI-segmentation#8]
Thank you for sharing code.
I try to test your code and the result is little bit tricky.
Because the output about 300 500 image is not bad.
However when we use high resolution image the result is quite poor.
Do you have any Idea why is it happen.
I change the annotation.csv so the box size is not the problem
![1](https://user-images.githubusercontent.com/9128330/84340838-3822b000-ab67-11ea-8a3f-f49e0fbcc383.jpg)
If you can see the images, the edge of the cloth is quite bad compare to your example.

**Comment by anish9** [comment]
@freaad, which version of the model was used here?

**Comment by freaad** [comment]
> @freaad, which version of the model was used here?

I just use your simple version 1.0 simple demo code actually.  The image size is really big as you can see.

**Comment by anish9** [comment]
@freaad, you can use the updated model and its limited to labels(top wear and dresses),
