### ISSUE TITLE
Very bad results

### ISSUE THREAD

**Issue by ayush9198gupta** [anish9/Fashion-AI-segmentation#9]
Hi @anish9 ,

I have followed your model for my approach but it is not giving good results on custom images.

Can you please suggest what I can do for best results.
![Screenshot from 2020-10-19 13-08-56](https://user-images.githubusercontent.com/61581309/96415663-89753700-120c-11eb-97f9-c544739685e7.png)

Thanks in advance

**Comment by anish9** [comment]
@ayush9198gupta ,
It works only for top wear clothes and full body dresses as of now, and the result of yours shows it has performed on extracting top wear.

**Comment by ayush9198gupta** [comment]
@anish9  I have simply use your updated check point and tested on my images and lts look like what i have shared also tested on full body dresses like gown but not working

**Comment by anish9** [comment]
@ayush9198gupta let me know which kind of image you tested.

**Comment by ayush9198gupta** [comment]
sharing one more example  as you said it works only for top wear clothes and full body dresses 
![Screenshot from 2020-10-19 13-23-27](https://user-images.githubusercontent.com/61581309/96416923-49af4f00-120e-11eb-8649-e2d5e0eb7063.png)

**Comment by anish9** [comment]
@ayush9198gupta the model is still vulnerable on hand portions of some ecommerce images, it is dataset issue with which model has some limitation. there are possible post processing techniques for skin removal out. you are encouraged to use that.
